package com.wx.movie.rec.dao.mapper;

import com.wx.movie.rec.dao.entity.UserReclist;

public interface UserReclistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reclist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reclist
     *
     * @mbggenerated
     */
    int insert(UserReclist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reclist
     *
     * @mbggenerated
     */
    int insertSelective(UserReclist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reclist
     *
     * @mbggenerated
     */
    UserReclist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reclist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserReclist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reclist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UserReclist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reclist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserReclist record);
}